#!/usr/bin/env python

import sys
import yaml

#amber mdinfo file
input = sys.stdin.read()

# get amber energy info from file

terms = input.replace("1-4 ","1-4_").split()

amber = {}
calorie = 4.184 # J
for i in range(0, len(terms), 3): # read amber energy data
    label = terms[i]
    if label in ["BOND", "ANGLE", "DIHED", "IMP",
            "EELEC", "1-4_EEL", "VDWAALS", "1-4_NB", "EPtot"]:
        value = float(terms[i+2])
        amber[label] = value*calorie

output = {}
output["bonds"] = amber["BOND"]
output["angles"] = amber["ANGLE"]
output["dihedrals"] = amber["DIHED"]
output["impropers"] = amber["IMP"]
output["total_coulomb"] = amber["EELEC"]+amber["1-4_EEL"]
output["coulomb_1-4"] = amber["1-4_EEL"]
output["total_vdw"] = amber["VDWAALS"]+amber["1-4_NB"]
output["vdw_1-4"] = amber["1-4_NB"]
output["total_potential"] = amber["EPtot"]

print(yaml.dump(output, default_flow_style=False))

