#!/usr/bin/env python

import sys
import yaml

#gromos log file
gromoslines = sys.stdin.readlines()

gromos = {}
num_energy_lines = 38
for l,line in enumerate(gromoslines):
    if line == "ENERGIES\n":
        energylines = gromoslines[l+1:l+num_energy_lines]
        break
for line in energylines:
    key, valuestr = line.split(':')
    key = key[2:].strip()
    value = float(valuestr)
    gromos[key] = float(value)

output = {}
output["bonds"] = gromos["Bonds"]
output["angles"] = gromos["Angles"]
output["dihedrals"] = gromos["Dihedral"]
output["impropers"] = gromos["Improper"]
output["total_coulomb"] = gromos["El (RF)"]
output["total_vdw"] = gromos["Vdw"]
output["total_potential"] = gromos["Potential"]

print(yaml.dump(output, default_flow_style=False))

