#!/usr/bin/env python

import sys
from lib.Topology import Topology

helpstring = "help\n"
if len(sys.argv) > 1:
    sys.stderr.write(helpstring)
    exit(1)

gromos_in = sys.stdin
amber_out = sys.stdout

topology = Topology(gromos_in)

topology.write_amber(amber_out)

exit(0)

